export const API_CALL_ERROR = "API_CALL_ERROR";
export const BEGIN_API_CALL = "BEGIN_API_CALL";

export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const REMOVE_TOKEN_SUCCESS = "REMOVE_TOKEN_SUCCESS";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
