export const API_CALL_ERROR = "API_CALL_ERROR";
export const BEGIN_API_CALL = "BEGIN_API_CALL";

export const LOAD_BBQS_SUCCESS = "LOAD_BBQS_SUCCESS";
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
