export const API_CALL_ERROR = "API_CALL_ERROR";
export const BEGIN_API_CALL = "BEGIN_API_CALL";

export const CREATE_BBQ_SUCCESS = "CREATE_BBQ_SUCCESS";
export const DELETE_BBQ_SUCCESS = "DELETE_BBQ_SUCCESS";
export const LOAD_BBQS_SUCCESS = "LOAD_BBQS_SUCCESS";
export const UPDATE_BBQ_SUCCESS = "UPDATE_BBQ_SUCCESS";

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const CREATE_FAVORITE_SUCCESS = "CREATE_FAVORITE_SUCCESS";
export const DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS";
export const UPDATE_FAVORITE_SUCCESS = "UPDATE_FAVORITE_SUCCESS";
export const LOAD_FAVORITE_SUCCESS = "LOAD_FAVORITE_SUCCESS";
